import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#302f2d",
        "surface-tint": "#5f5e5e",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#999693",
        "inverse-surface": "#2d3133",
        "primary-container": "#2f2f2f",
        "on-primary-fixed-variant": "#474747",
        secondary: "#505f76",
        "surface-container-high": "#e6e8ea",
        tertiary: "#1b1a19",
        "tertiary-fixed": "#e6e2de",
        "outline-variant": "#c4c7c7",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#989696",
        "primary-fixed": "#e4e2e1",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1c1b1a",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#484644",
        "on-primary-fixed": "#1b1c1c",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#c9c6c3",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        surface: "#f7f9fb",
        "on-secondary-container": "#54647a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        primary: "#1a1a1a",
        error: "#ba1a1a",
        "primary-fixed-dim": "#c8c6c6",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface-variant": "#444748",
        "secondary-container": "#d0e1fb",
        background: "#f7f9fb",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        outline: "#747878",
        "inverse-primary": "#c8c6c6",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        margin_mobile: "16px",
        xl: "32px",
        margin_desktop: "32px",
        md: "16px",
        base_unit: "4px",
        xs: "4px",
        lg: "24px",
        sm: "8px",
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      boxShadow: {
        ambient: "0 4px 24px -4px rgba(0,0,0,0.03), 0 2px 8px -2px rgba(0,0,0,0.02)",
        "ambient-hover": "0 8px 32px -8px rgba(0,0,0,0.06), 0 4px 12px -4px rgba(0,0,0,0.04)",
      },
    },
  },
  plugins: [],
} satisfies Config;
